### ISSUE TITLE
SMF issue during install with utmp

### ISSUE THREAD

**Issue by esproul** [omniti-labs/kayak#10]
Noticed that during an r151014 Kayak install, svc:/system/utmp:default went into maintenance because the utmpd executable (/usr/lib/utmpd) was missing.  SMF reported an exit status of 96 from the start method.  The relevant code is here:

http://src.illumos.org/source/xref/illumos-gate/usr/src/cmd/utmpd/svc-utmpd#29

http://src.illumos.org/source/xref/illumos-gate/usr/src/cmd/svc/shell/smf_include.sh#240 shows that SMF_EXIT_ERR_CONFIG is indeed 96.

This wasn't fatal to the installed system (the install was already done) but it did stall Kayak and force a maintenance login.

It looks like we toss the utmp SMF manifest in build_image.sh though, so I'm not sure what the correct fix is.  Maybe we just keep utmpd, or maybe we don't need utmp at all in the miniroot/breakfix environment?

**Comment by danmcd** [comment]
I'd throw in /usr/lib/utmpd to be safe.  Unless there's an impending size limit, we should be in decent shape.

**Comment by danmcd** [comment]
Bringing this one back from the dead.  Whaddya say to this?

<pre>
diff --git a/data/known_extras b/data/known_extras
index f2a5cc0..7ceb76c 100644
--- a/data/known_extras
+++ b/data/known_extras
@@ -35,6 +35,7 @@
 0 /usr/bin/svcs
 0 /usr/sbin/svccfg
 0 /usr/sbin/zstreamdump
+0 /usr/lib/utmpd
 0 /lib/libintl.so.1
 0 /usr/bin/less
 0 /usr/bin/more
</pre>

**Comment by esproul** [comment]
LGTM

**Comment by danmcd** [comment]
Closed.
