### ISSUE TITLE
Want nvme support in Kayak

### ISSUE THREAD

**Issue by esproul** [omniti-labs/kayak#11]
I'm stashing this here because I'll soon have test h/w and will probably end up doing it myself.  If someone else gets to it sooner, so much the better.

We should support installing to nvme devices.  Since Kayak does not use libdiskmgmt, we don't need to wait for https://www.illumos.org/issues/6232 .

**Comment by esproul** [comment]
Hmm... catching up on illumos-developer list activity, we are probably going to need 6299-6301 changes before we'll be able to install on nvme(7D) devices, because Kayak uses format(1M) to get device names.  It sounds like without these changes, Kayak won't see devices either.

https://marc.info/?l=illumos-developer&m=144430878214354&w=2

**Comment by danmcd** [comment]
We'll need that as a dependency for sure.

**Comment by esproul** [comment]
My test h/w arrived and I found that format(1M) does indeed already see blkdev devices.  It just can't display vendor/model/firmware info (which is what 6301 should fix).  Hypothetically Kayak should be able to install on these devices, assuming the admin can properly identify their logical disk IDs in the client config.

I'll start by getting a miniroot and ZFS image containing nvme(7D).

**Comment by danmcd** [comment]
I'm creating the r151016 branch of kayak today.  Make sure this lands in that branch as well.

**Comment by esproul** [comment]
@danmcd will do.

**Comment by esproul** [comment]
I have some changes that permit *install* on nvme, but my test h/w doesn't permit booting from nvme, as far as I can tell.  The changes are in two parts:

1. Install/preserve nvme driver and conf file in miniroot generation (build_image.sh, data/kernel)
2. Install nvme along with entire during ZFS image generation (build_zfs_image.sh)

I think having 1 is fine, and will work if/when nvme is part of entire.  I don't really want to put 2 in because it feels hacky, but right now it is required if you want to boot off nvme, though I can't test it with the hardware I have.

**Comment by danmcd** [comment]
Feel free to pull-request this or mail me a "git format-patch".

**Comment by danmcd** [comment]
Closing since I merged the two above.

**Comment by danmcd** [comment]
NOTE:  I just put the kayak diff (which was only in r151014) into both master and r151016.
