### ISSUE TITLE
DNS does not seem to work in kayak

### ISSUE THREAD

**Issue by sjorge** [omniti-labs/kayak#6]
It seems DNS is not working within kayak.
I had a quick look by setting NO_REBOOT but it seems even if you configure resolv.conf and nsswitch.conf it still doesn't work. I think libresolv is missing?

**Comment by danmcd** [comment]
(Pardon the latency.) I do not see libresolv in any of the files in data/, which is where you put it.  I'll try building a .gz and a .zfs.bz2 later, or you can alter one of the files in data (probably access.log) to add libresolv.  Make sure you include anything it needs as well, and include both 64- and 32- bit versions.

**Comment by danmcd** [comment]
@sjorge - How about this?

<pre>
bloody(~/ws/kayak)[0]% git diff
diff --git a/data/access.log b/data/access.log
index d9f35ab..b5773a6 100644
--- a/data/access.log
+++ b/data/access.log
@@ -1477,3 +1477,7 @@
 20872055 /usr/lib/libsmbios.so.1
 20872055 /usr/lib/amd64/libsmbios.so
 20872055 /usr/lib/amd64/libsmbios.so.1
+20872055 /lib/libresolv.so.1
+20872055 /lib/libresolv.so.2
+20872055 /usr/lib/libresolv.so.1
+20872055 /usr/lib/libresolv.so.2
bloody(~/ws/kayak)[0]% 
</pre>
